
title: Kellie Thomsen
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Civil ENgineer with a MAster of Data Science. I'm interested in NLP an Machione Learning and working my way to gain the AZ900 Certification. 
  <br><br>
  <a href="https://www.linkedin.com/in/kellie-thomsen/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#34276f'
